### ISSUE TITLE
The plugin is not working anymore

### ISSUE THREAD

**Issue by BarbzYHOOL** [morphje/ansible_pass_lookup#10]
I use any of the example here https://docs.ansible.com/ansible/latest/plugins/lookup/passwordstore.html

And they all return the same thing:
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_setup_payload_IDncQz/ansible_setup_payload.zip/ansible/module_utils/basic.py", line 2866, in run_command
    rfds, wfds, efds = select.select(rpipes, [], rpipes, 1)
  File "/tmp/ansible_setup_payload_IDncQz/ansible_setup_payload.zip/ansible/module_utils/facts/timeout.py", line 37, in _handle_timeout
    raise TimeoutError(msg)
TimeoutError: Timer expired after 10 seconds

fatal: [localhost]: FAILED! => changed=false 
  cmd: /bin/findmnt --list --noheadings --notruncate
  invocation:
    module_args:
      fact_path: /etc/ansible/facts.d
      filter: '*'
      gather_subset:
      - all
      gather_timeout: 10
  msg: Timer expired after 10 seconds
  rc: 257
 ```

I'm on ansible 2.7 on ubuntu and I've just installed "pass" and it works fine (added my new gpg key etc)

**Comment by BarbzYHOOL** [comment]
Ok, I think it's more like a general ansible issue, there is one opened issue related https://github.com/ansible/ansible/issues/43884
